---
- name: Configuring
  template: >
    src={{ vsftpd_config_template if vsftpd_config_template else 'etc-vsftpd.conf.j2' }}
    dest=/etc/vsftpd.conf
    owner=root
    group=root
    mode=0644
  notify: restart vsftpd
  tags:
    - networking
    - vsftpd
    - config

- name: Configuring
  template: >
    src={{ vsftpd_userlist_template if vsftpd_userlist_template else 'etc-vsftpd.userlist.j2' }}
    dest=/etc/vsftpd.userlist
    owner=root
    group=root
    mode=0644
  notify: restart vsftpd
  tags:
    - networking
    - vsftpd
    - config

- name: Adding nologin shell
  lineinfile: >
    state=present
    dest=/etc/shells
    line="/usr/sbin/nologin"
    regexp="^/usr/sbin/nologin"
    insertafter=EOF
  tags:
    - networking
    - vsftpd
    - config
- name: Adding hosts_allow
  lineinfile: >
    state=present
    dest=/etc/hosts.allow
    line="vsftpd:100.0.0.100"
    regexp="^vsftpd:100.0.0.100"
    insertafter=EOF
  tags:
    - networking
    - vsftpd
    - config

- name: Adding hosts deny
  lineinfile: >
    state=present
    dest=/etc/hosts.deny
    line="vsftpd:ALL"
    regexp="^vsftpd:ALL"
    insertafter=EOF
  tags:
    - networking
    - vsftpd
    - config
