---

- name: Install ProFTPD (apt)
  apt: 
    name: proftpd-basic
    state: present

- name: Mkdir For Virtual User
  file:
    path: /home/{{ FTP_USER }}
    owner: 1024
    group: 1024
    mode:  0700
    state: directory

- name: Mkdir proftpd Folder
  file:
    path: /usr/local/etc/proftpd
    state: directory

- name: Set FTP User's Password
  shell: echo {{ FTP_PASS }}|ftpasswd --passwd --file=/usr/local/etc/proftpd/passwd --name={{ FTP_USER }} --uid=1024 --home=/home/{{ FTP_USER }} --shell=/bin/false --stdin
 
- name: Set FTP Group
  shell: ftpasswd --file=/usr/local/etc/proftpd/group --group --name=virtualusers --gid=1024

- name: Add FTP User to Group
  shell: ftpasswd --group --name=virtualusers --gid=1024 --member={{ FTP_USER }} --file=/usr/local/etc/proftpd/group

- name: Copy Configuration
  template: src=proftpd.conf dest=/etc/proftpd/proftpd.conf backup=yes
  
- debug: msg="restart proftp"
  notify: 
    proftpd restart
  changed_when: true
