---

- name: install samba
  apt:
    name: samba
    state: present

- name: add samba user
  #command: useradd -M -s /sbin/nologin {{ SAMBA_USERNAME }}
  user:
    name: "{{ SMB_USER }}"
    shell: /sbin/nogin
    createhome: no

- name: smbpasswd
  shell: "(echo {{ SMB_PASS }}; echo {{ SMB_PASS }}) | smbpasswd -a -s {{ SMB_USER }}"

- name: smbpasswd enable
  command: smbpasswd -e {{ SMB_USER }}

- name: create group
  command: groupadd {{ SMB_GROUP }}

- name: usermod
  command: usermod -G {{ SMB_GROUP }} {{ SMB_USER }}

- name: mkdir /srv/samba/guest
  file:
    path: /srv/{{ item }}
    mode: 2775
    group: "{{ SMB_GROUP }}"
    state: directory
  with_items: [samba,samba/guest]

- name: mkdir /srv/samba/demo
  file:
    path: /srv/samba/demo
    mode: 2770
    group: "{{ SMB_GROUP }}"
    state: directory

- name: alter and copy smb.conf
  template: src=smb.conf dest=/etc/samba/smb.conf backup=yes
  notify:
    - smbd stop
    - smbd start
