---

- hosts: all
  sudo: yes
  roles:
    - franklinkim.vsftpd
    - indigo-dc.nfs
    - debops.dhcpd
    - mrlesmithjr.samba
    - resmo.bind
  vars:

# vsftpd Server
    vsftpd_service_enabled: yes
    vsftpd_service_state: started
    vsftpd_users:
       - username: 'ftpuser'
         name: 'FTP User'
#         password: '123'
         password: !vault |
                   $ANSIBLE_VAULT;1.1;AES256
                   62623332373539643139356239323330323837393837333336316235623865623738373865323265
                   3132376138333431633832393066636430366637636431310a323437623964396435343464336631
                   63326465363231303164316430383434643432363232386361643064313937623662616564313961
                   6365663234316335360a326331313463663864333762313036356565336337653864653233303836
                   6530                

    vsftpd_config:
         local_enable: YES
         anonymous_enable: YES
         chroot_local_user: YES
         write_enable: YES

         user_sub_token: $USER
         local_root: '/home/$USER/ftp'

         pasv_min_port: '40000'
         pasv_max_port: '50000'

         userlist_enable: YES
         userlist_file: '/etc/vsftpd.userlist'
         userlist_deny: NO

         tcp_wrappers: YES

    vsftpd_userlist:
         user_1: 'anonymous'
         user_2: 'ftpuser'

# NFS Server
    # NFS install mode: server or client
    nfs_mode: 'server'
    # Line to add to the /etc/exports file
    nfs_exports:
      - path: "/var/nfs/share_rw"
        export: "100.0.0.100(rw,sync,no_subtree_check)"
      - path: "/var/nfs/share_r"
        export: "100.0.0.100(ro,sync,no_subtree_check)"

# DHCP Server
    dhcpd_mode: 'server'
    dhcpd_ipversion: '4'
    dhcpd_interfaces: ['enp0s9']

    dhcpd_subnets:
      - subnet: '100.0.0.0'
        netmask: '255.255.255.0'
        routers: '100.0.0.100'
        options: |
          default-lease-time 600;
          max-lease-time 7200;
        pools:
          - comment: "A pool in a subnet"
            range: '100.0.0.100 100.0.0.200'

# SAMBA Server
    # Define samba groups to create
    samba_groups:
      - 'sambaGroup'
    # Define users to create
    samba_users:
        # Define user name to create
      - name: 'sambauser'
        # Define groups to add user to
        # ensure samba_groups names exist.
        groups:
          - 'sambaGroup'
        smbpasswd: '123'
    # Defines root folder for samba shares to be created
    samba_share_path: '/srv/samba'
    samba_shares:
      - name: 'demo'
        browsable: 'yes'

        group: 'nogroup'
        read_only: 'no'
        guest_ok: 'no'

        force_create_mode: '0660'
        force_directory_mode: '2770'
        folder_perms: '0770'

        force_user: 'sambauser'
        force_group: 'sambaGroup'

        writable: 'yes'

# DNS Server
    bind_masterzones_path: 'masters'
    bind_config_master_zones:
      - name: 'cuc.edu.cn'
