---

- name: install bin9
  apt:
     name: bind9
     state: present
 
- name: copy db.cuc.edu.cn
  template: src=db.cuc.edu.cn dest=/etc/bind/db.cuc.edu.cn

- name: copy named.conf.local and restart bind9
  template: src=named.conf.local dest=/etc/bind/named.conf.local backup=yes
  notify: 
     - dns restart
