---
- name: Install vsftpd package and update 
  apt: 
    name: vsftpd
    state: present
    update_cache: yes
- name: mkdir /workspace
  file:
    path: /home/workspace
    state: directory
- name: copy the vsftpd.conf
  template: src=vsftpd.conf dest=/etc/vsftpd.conf backup=yes

- name: copy the vsftpd.userlist
  template: src=vsftpd.userlist dest=/etc/vsftpd.userlist backup=yes

- name: copy the hosts.allow
  template: src=hosts.allow dest=/etc/hosts.allow backup=yes

- name: copy the hosts.deny
  template: src=hosts.deny dest=/etc/hosts.deny backup=yes

- name: add vsftpd user
  user:
    name: "{{ ftpnfsuser }}"
    shell: /sbin/nogin
    createhome: yes
    password: "{{ ftpnfspassword }}"
    update_password: always

- name: mkdir ftp directory
  file:
     path: /var/ftp
     state: directory
  file:
     path: /home/{{ ftpnfsuser }}/ftp
     state: directory
     owner: nobody
     group: nogroup
  file:
     path: /home/{{ ftpnfsuser }}/ftp/files
     state: directory
     owner: "{{ ftpnfsuser }}"
     group: "{{ ftpnfsuser }}"
- name: build ssl cert
  shell: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.pem -out /etc/ssl/private/vsftpd.pem -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"
  notify: 
    - restart vsftpd
