---

- name: install samba
  apt:
    name: samba
    state: present

- name: add samba user
  #command: useradd -M -s /sbin/nologin {{ SAMBA_USERNAME }}
  user:
    name: "{{ SAMBA_USERNAME }}"
    shell: /sbin/nogin
    createhome: no

- name: passwd
  shell: "(echo {{ SAMBA_PASSWORD }}; echo {{ SAMBA_PASSWORD }})  | passwd {{ SAMBA_USERNAME }}"

- name: smbpasswd
  shell:  "(echo {{ SAMBA_PASSWORD }}; echo {{ SAMBA_PASSWORD }})  | smbpasswd -a -s {{ SAMBA_USERNAME }}"

- name: smbpasswd enable
  command: smbpasswd -e {{ SAMBA_USERNAME }}

- name: create group
  group:
    name: "{{ SAMBA_GROUP }}"
    state: present

- name: usermod
  command: usermod -G {{ SAMBA_GROUP }} {{ SAMBA_USERNAME }}

- name: mkdir /srv/samba/guest
  file:
    path: /srv/{{ item }}
    mode: "{{ SAMBA_GUEST_LIMIT }}"
    group: "{{ SAMBA_GROUP }}"
    state: directory
  with_items: [samba,samba/guest]

- name: mkdir /srv/samba/demo
  file:
    path: "{{ SAMBA_DEMO_DIR }}"
    mode: "{{ SAMBA_DEMO_LIMIT }}"
    group: "{{ SAMBA_GROUP }}"
    state: directory

