---

- name: install nfs-kernel-server
  apt:
    name: nfs-kernel-server
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 300

- name: mkdir /var/nfs/general
  file:
    path: /var/nfs/general
    owner: nobody
    group: nogroup
    state: directory

- name: alter and copy exports
  template: src=exports dest=/etc/exports backup=yes
  notify:
    - nfs-kernel-server restart


