---

- name: install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: up the interface
  shell: ifconfig {{ INTERNAL_INTER }} up

- name: set the ip of interface
  shell: ifconfig {{ INTERNAL_INTER }} {{ INTERNAL_IP }} netmask {{ INTERNAL_NETMASK }}
