---

- name: alter and copy isc-dhcp-server
  template: src=isc-dhcp-server dest=/etc/default/isc-dhcp-server backup=yes
#  notify:
#    - smbd stop
#    - smbd start

- name:  alter and copy dhcpd.conf
  template: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf

- name: restart dhcp
  service: 
    name: isc-dhcp-server
    state: restarted
